parameter_defaults:
  DeployedNetworkEnvironment:
    net_attributes_map:
      data_vlan:
        network:
          dns_domain: datavlan.maas.
          mtu: 1500
          name: data_vlan
          tags:
          - tripleo_network_name=DataVlan
          - tripleo_net_idx=2
        subnets:
          data_vlan_subnet:
            cidr: 172.22.45.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: data_vlan_subnet
            tags:
            - tripleo_vlan_id=45
      external:
        network:
          dns_domain: external.maas.
          mtu: 1500
          name: external
          tags:
          - tripleo_network_name=External
          - tripleo_vip=true
          - tripleo_net_idx=3
        subnets:
          external_subnet:
            cidr: 172.22.40.0/24
            dns_nameservers: []
            gateway_ip: 172.22.40.1
            host_routes: []
            ip_version: 4
            name: external_subnet
            tags:
            - tripleo_vlan_id=40
      internal_api:
        network:
          dns_domain: internalapi.maas.
          mtu: 1500
          name: internal_api
          tags:
          - tripleo_net_idx=0
          - tripleo_network_name=InternalApi
          - tripleo_vip=true
        subnets:
          internal_api_subnet:
            cidr: 172.22.41.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: internal_api_subnet
            tags:
            - tripleo_vlan_id=41
      tenant:
        network:
          dns_domain: tenant.maas.
          mtu: 1500
          name: tenant
          tags:
          - tripleo_network_name=Tenant
          - tripleo_net_idx=1
        subnets:
          tenant_subnet:
            cidr: 172.22.44.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: tenant_subnet
            tags:
            - tripleo_vlan_id=44
    net_cidr_map:
      data_vlan:
      - 172.22.45.0/24
      external:
      - 172.22.40.0/24
      internal_api:
      - 172.22.41.0/24
      tenant:
      - 172.22.44.0/24
    net_ip_version_map:
      data_vlan: 4
      external: 4
      internal_api: 4
      tenant: 4
resource_registry:
  OS::TripleO::Network: /usr/share/openstack-tripleo-heat-templates/network/deployed_networks.yaml
