parameter_defaults:
  ControllerNetworkConfigTemplate: '~/tripleo-overcloud-deploy/nic-config/multiple_nics_ctl.j2'
  ComputeNetworkConfigTemplate: '~/tripleo-overcloud-deploy/nic-config/multiple_nics_comp.j2'
